version: '3.8'

networks:
  prod:

services:
  web_server:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './frontend/nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt' 
    depends_on:
      - api_backend
      - frontend_app
    networks:
      - prod

  api_backend:
    build:
      context: ./backend
    env_file: 
      - ./.env
    networks:
      - prod
    volumes:
      - ./backend:/app

  frontend_app:
    build:
      context: ./frontend
    env_file: 
      - ./.env
    networks:
      - prod
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"

  portainer_service:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
