name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine changed files
        id: changed-files
        run: |
          echo "CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)" >> $GITHUB_ENV

      - name: Deploy Frontend
        if: ${{ env.CHANGED_FILES }} && contains(env.CHANGED_FILES, 'frontend/')
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: echo "Frontend changes detected, deploying frontend"

      - name: SSH Deploy Frontend via Docker Compose
        if: ${{ env.CHANGED_FILES }} && contains(env.CHANGED_FILES, 'frontend/')
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << 'EOF'
            cd /root/core/meatIsland
            git pull
            docker-compose down
            docker-compose up -d --build
            sudo systemctl restart nginx
          EOF

      - name: Deploy Backend
        if: ${{ env.CHANGED_FILES }} && contains(env.CHANGED_FILES, 'backend/')
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: echo "Backend changes detected, deploying backend"

      - name: SSH Deploy Backend via Docker Compose
        if: ${{ env.CHANGED_FILES }} && contains(env.CHANGED_FILES, 'backend/')
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} << 'EOF'
            cd /root/core/meatIsland
            git pull
            docker-compose down
            docker-compose up -d --build
            sudo systemctl restart nginx
          EOF
